// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package nmosdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDevice = `-- name: GetDevice :one
SELECT id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version, meta_created_at FROM devices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Type,
		&i.Receivers,
		&i.Senders,
		&i.NodeID,
		&i.Controls,
		&i.MetaUserLabel,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const getDeviceByReceiver = `-- name: GetDeviceByReceiver :one
SELECT id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version, meta_created_at FROM devices D
WHERE D.id = (
    SELECT device_id FROM receivers R
    WHERE R.id = $1 LIMIT 1
) LIMIT 1
`

func (q *Queries) GetDeviceByReceiver(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByReceiver, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Type,
		&i.Receivers,
		&i.Senders,
		&i.NodeID,
		&i.Controls,
		&i.MetaUserLabel,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version, meta_created_at FROM devices
ORDER BY id
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Type,
			&i.Receivers,
			&i.Senders,
			&i.NodeID,
			&i.Controls,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByCreatedSince = `-- name: ListDevicesByCreatedSince :many
SELECT id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version, meta_created_at FROM devices
WHERE meta_created_at >= $1
ORDER BY meta_created_at
`

func (q *Queries) ListDevicesByCreatedSince(ctx context.Context, createdSince pgtype.Timestamptz) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByCreatedSince, createdSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Type,
			&i.Receivers,
			&i.Senders,
			&i.NodeID,
			&i.Controls,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByNodeID = `-- name: ListDevicesByNodeID :many
SELECT id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version, meta_created_at FROM devices
WHERE node_id = $1
ORDER BY id
`

func (q *Queries) ListDevicesByNodeID(ctx context.Context, nodeID *uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByNodeID, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Type,
			&i.Receivers,
			&i.Senders,
			&i.NodeID,
			&i.Controls,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesPaginated = `-- name: ListDevicesPaginated :many
SELECT id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version, meta_created_at FROM devices
WHERE id >= $1
ORDER BY id
LIMIT $2
`

type ListDevicesPaginatedParams struct {
	StartingID uuid.UUID
	PageSize   int32
}

func (q *Queries) ListDevicesPaginated(ctx context.Context, arg ListDevicesPaginatedParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesPaginated, arg.StartingID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Type,
			&i.Receivers,
			&i.Senders,
			&i.NodeID,
			&i.Controls,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (
    id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) 
DO UPDATE
SET
    resource_version = EXCLUDED.resource_version,
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    type = EXCLUDED.type,
    receivers = EXCLUDED.receivers,
    senders = EXCLUDED.senders,
    node_id = EXCLUDED.node_id,
    controls = EXCLUDED.controls,
    meta_user_label = EXCLUDED.meta_user_label
WHERE
    devices.meta_api_version = EXCLUDED.meta_api_version
    AND devices.resource_version < EXCLUDED.resource_version
RETURNING id, resource_version, label, description, tags, type, receivers, senders, node_id, controls, meta_user_label, meta_api_version, meta_created_at
`

type UpsertDeviceParams struct {
	ID              uuid.UUID
	ResourceVersion string
	Label           string
	Description     *string
	Tags            []byte
	Type            string
	Receivers       []string
	Senders         []string
	NodeID          *uuid.UUID
	Controls        []byte
	MetaUserLabel   *string
	MetaApiVersion  string
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.ResourceVersion,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Type,
		arg.Receivers,
		arg.Senders,
		arg.NodeID,
		arg.Controls,
		arg.MetaUserLabel,
		arg.MetaApiVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Type,
		&i.Receivers,
		&i.Senders,
		&i.NodeID,
		&i.Controls,
		&i.MetaUserLabel,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}
