// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flows.sql

package nmosdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFlow = `-- name: GetFlow :one
SELECT id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at FROM flows
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFlow(ctx context.Context, id uuid.UUID) (Flow, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.SourceID,
		&i.DeviceID,
		&i.Parents,
		&i.GrainRate,
		&i.Format,
		&i.MediaType,
		&i.FrameWidth,
		&i.FrameHeight,
		&i.InterlaceMode,
		&i.Colorspace,
		&i.TransferCharacteristic,
		&i.Components,
		&i.SampleRate,
		&i.BitDepth,
		&i.EventType,
		&i.DidSdid,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const listFlows = `-- name: ListFlows :many
SELECT id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at FROM flows
ORDER BY id
`

func (q *Queries) ListFlows(ctx context.Context) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.SourceID,
			&i.DeviceID,
			&i.Parents,
			&i.GrainRate,
			&i.Format,
			&i.MediaType,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.TransferCharacteristic,
			&i.Components,
			&i.SampleRate,
			&i.BitDepth,
			&i.EventType,
			&i.DidSdid,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsByCreatedSince = `-- name: ListFlowsByCreatedSince :many
SELECT id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at FROM flows
WHERE meta_created_at >= $1
ORDER BY meta_created_at
`

func (q *Queries) ListFlowsByCreatedSince(ctx context.Context, createdSince pgtype.Timestamptz) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlowsByCreatedSince, createdSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.SourceID,
			&i.DeviceID,
			&i.Parents,
			&i.GrainRate,
			&i.Format,
			&i.MediaType,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.TransferCharacteristic,
			&i.Components,
			&i.SampleRate,
			&i.BitDepth,
			&i.EventType,
			&i.DidSdid,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsByDeviceID = `-- name: ListFlowsByDeviceID :many
SELECT id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at FROM flows
WHERE device_id = $1
ORDER BY id
`

func (q *Queries) ListFlowsByDeviceID(ctx context.Context, deviceID *uuid.UUID) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlowsByDeviceID, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.SourceID,
			&i.DeviceID,
			&i.Parents,
			&i.GrainRate,
			&i.Format,
			&i.MediaType,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.TransferCharacteristic,
			&i.Components,
			&i.SampleRate,
			&i.BitDepth,
			&i.EventType,
			&i.DidSdid,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsByDeviceIDAndFormat = `-- name: ListFlowsByDeviceIDAndFormat :many
SELECT id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at FROM flows
WHERE device_id = $1 AND format = $2
ORDER BY id
`

type ListFlowsByDeviceIDAndFormatParams struct {
	DeviceID *uuid.UUID
	Format   string
}

func (q *Queries) ListFlowsByDeviceIDAndFormat(ctx context.Context, arg ListFlowsByDeviceIDAndFormatParams) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlowsByDeviceIDAndFormat, arg.DeviceID, arg.Format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.SourceID,
			&i.DeviceID,
			&i.Parents,
			&i.GrainRate,
			&i.Format,
			&i.MediaType,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.TransferCharacteristic,
			&i.Components,
			&i.SampleRate,
			&i.BitDepth,
			&i.EventType,
			&i.DidSdid,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsByFormat = `-- name: ListFlowsByFormat :many
SELECT id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at FROM flows
WHERE format = $1
ORDER BY id
`

func (q *Queries) ListFlowsByFormat(ctx context.Context, format string) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlowsByFormat, format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.SourceID,
			&i.DeviceID,
			&i.Parents,
			&i.GrainRate,
			&i.Format,
			&i.MediaType,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.TransferCharacteristic,
			&i.Components,
			&i.SampleRate,
			&i.BitDepth,
			&i.EventType,
			&i.DidSdid,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsPaginated = `-- name: ListFlowsPaginated :many
SELECT id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at FROM flows
WHERE id >= $1
ORDER BY id
LIMIT $2
`

type ListFlowsPaginatedParams struct {
	StartingID uuid.UUID
	PageSize   int32
}

func (q *Queries) ListFlowsPaginated(ctx context.Context, arg ListFlowsPaginatedParams) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlowsPaginated, arg.StartingID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.SourceID,
			&i.DeviceID,
			&i.Parents,
			&i.GrainRate,
			&i.Format,
			&i.MediaType,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.TransferCharacteristic,
			&i.Components,
			&i.SampleRate,
			&i.BitDepth,
			&i.EventType,
			&i.DidSdid,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFlow = `-- name: UpsertFlow :one
INSERT INTO flows (
    id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
)
ON CONFLICT (id) 
DO UPDATE
SET
    resource_version = EXCLUDED.resource_version,
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    source_id = EXCLUDED.source_id,
    device_id = EXCLUDED.device_id,
    parents = EXCLUDED.parents,
    grain_rate = EXCLUDED.grain_rate,
    format = EXCLUDED.format,
    media_type = EXCLUDED.media_type,
    frame_width = EXCLUDED.frame_width,
    frame_height = EXCLUDED.frame_height,
    interlace_mode = EXCLUDED.interlace_mode,
    colorspace = EXCLUDED.colorspace,
    transfer_characteristic = EXCLUDED.transfer_characteristic,
    components = EXCLUDED.components,
    sample_rate = EXCLUDED.sample_rate,
    bit_depth = EXCLUDED.bit_depth,
    event_type = EXCLUDED.event_type,
    did_sdid = EXCLUDED.did_sdid
WHERE
    flows.meta_api_version = EXCLUDED.meta_api_version
    AND flows.resource_version < EXCLUDED.resource_version
RETURNING id, resource_version, label, description, tags, source_id, device_id, parents, grain_rate, format, media_type, frame_width, frame_height, interlace_mode, colorspace, transfer_characteristic, components, sample_rate, bit_depth, event_type, did_sdid, meta_api_version, meta_created_at
`

type UpsertFlowParams struct {
	ID                     uuid.UUID
	ResourceVersion        string
	Label                  string
	Description            *string
	Tags                   []byte
	SourceID               *uuid.UUID
	DeviceID               *uuid.UUID
	Parents                []uuid.UUID
	GrainRate              []byte
	Format                 string
	MediaType              *string
	FrameWidth             *int32
	FrameHeight            *int32
	InterlaceMode          *string
	Colorspace             *string
	TransferCharacteristic *string
	Components             []byte
	SampleRate             []byte
	BitDepth               *int32
	EventType              *string
	DidSdid                []byte
	MetaApiVersion         string
}

func (q *Queries) UpsertFlow(ctx context.Context, arg UpsertFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, upsertFlow,
		arg.ID,
		arg.ResourceVersion,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.SourceID,
		arg.DeviceID,
		arg.Parents,
		arg.GrainRate,
		arg.Format,
		arg.MediaType,
		arg.FrameWidth,
		arg.FrameHeight,
		arg.InterlaceMode,
		arg.Colorspace,
		arg.TransferCharacteristic,
		arg.Components,
		arg.SampleRate,
		arg.BitDepth,
		arg.EventType,
		arg.DidSdid,
		arg.MetaApiVersion,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.SourceID,
		&i.DeviceID,
		&i.Parents,
		&i.GrainRate,
		&i.Format,
		&i.MediaType,
		&i.FrameWidth,
		&i.FrameHeight,
		&i.InterlaceMode,
		&i.Colorspace,
		&i.TransferCharacteristic,
		&i.Components,
		&i.SampleRate,
		&i.BitDepth,
		&i.EventType,
		&i.DidSdid,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}
