// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package nmosdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID              uuid.UUID
	ResourceVersion string
	Label           string
	Description     *string
	Tags            []byte
	Type            string
	Receivers       []string
	Senders         []string
	NodeID          *uuid.UUID
	Controls        []byte
	MetaApiVersion  string
	MetaCreatedAt   pgtype.Timestamptz
}

type Flow struct {
	ID                     uuid.UUID
	ResourceVersion        string
	Label                  string
	Description            *string
	Tags                   []byte
	SourceID               *uuid.UUID
	DeviceID               *uuid.UUID
	Parents                []uuid.UUID
	GrainRate              []byte
	Format                 string
	MediaType              *string
	FrameWidth             *int32
	FrameHeight            *int32
	InterlaceMode          *string
	Colorspace             *string
	TransferCharacteristic *string
	Components             []byte
	SampleRate             []byte
	BitDepth               *int32
	EventType              *string
	DidSdid                []byte
	MetaApiVersion         string
	MetaCreatedAt          pgtype.Timestamptz
}

type Node struct {
	ID              uuid.UUID
	ResourceVersion string
	Label           string
	Description     *string
	Tags            []byte
	ApiVersions     []string
	ApiEndpoints    []byte
	Caps            []byte
	Services        []byte
	Clocks          []byte
	Interfaces      []byte
	MetaApiVersion  string
	MetaCreatedAt   pgtype.Timestamptz
}

type Receiver struct {
	ID                 uuid.UUID
	ResourceVersion    string
	Label              string
	Description        *string
	Tags               []byte
	DeviceID           *uuid.UUID
	Transport          *string
	InterfaceBindings  []string
	SubscriptionSender *uuid.UUID
	SubscriptionActive pgtype.Bool
	Format             *string
	Caps               []byte
	MetaApiVersion     string
	MetaCreatedAt      pgtype.Timestamptz
}

type Sender struct {
	ID                   uuid.UUID
	ResourceVersion      string
	Label                string
	Description          *string
	Tags                 []byte
	Caps                 []byte
	FlowID               *uuid.UUID
	Transport            string
	DeviceID             *uuid.UUID
	ManifestHref         *string
	InterfaceBindings    []string
	SubscriptionReceiver *uuid.UUID
	SubscriptionActive   pgtype.Bool
	TransportFile        []byte
	MetaApiVersion       string
	MetaCreatedAt        pgtype.Timestamptz
}

type Source struct {
	ID              uuid.UUID
	ResourceVersion string
	Label           string
	Description     *string
	Tags            []byte
	GrainRate       []byte
	Caps            []byte
	DeviceID        *uuid.UUID
	Parents         []string
	ClockName       *string
	Format          string
	AudioChannels   []byte
	MetaApiVersion  string
	MetaCreatedAt   pgtype.Timestamptz
}
