// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package nmosdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNode = `-- name: GetNode :one
SELECT id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version, meta_created_at FROM nodes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.ApiVersions,
		&i.ApiEndpoints,
		&i.Caps,
		&i.Services,
		&i.Clocks,
		&i.Interfaces,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const getNodeByDevice = `-- name: GetNodeByDevice :one
SELECT id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version, meta_created_at FROM nodes N
WHERE N.id = (
    SELECT node_id FROM devices D
    WHERE D.id = $1 LIMIT 1
) LIMIT 1
`

func (q *Queries) GetNodeByDevice(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByDevice, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.ApiVersions,
		&i.ApiEndpoints,
		&i.Caps,
		&i.Services,
		&i.Clocks,
		&i.Interfaces,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const getNodeByReceiver = `-- name: GetNodeByReceiver :one
SELECT id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version, meta_created_at FROM nodes N
WHERE N.id = (
    SELECT node_id FROM devices D
    WHERE D.id = (
        SELECT device_id FROM receivers R
        WHERE R.id = $1 LIMIT 1
    ) LIMIT 1
) LIMIT 1
`

func (q *Queries) GetNodeByReceiver(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByReceiver, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.ApiVersions,
		&i.ApiEndpoints,
		&i.Caps,
		&i.Services,
		&i.Clocks,
		&i.Interfaces,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version, meta_created_at FROM nodes
ORDER BY id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.ApiVersions,
			&i.ApiEndpoints,
			&i.Caps,
			&i.Services,
			&i.Clocks,
			&i.Interfaces,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByCreatedSince = `-- name: ListNodesByCreatedSince :many
SELECT id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version, meta_created_at FROM nodes
WHERE meta_created_at >= $1
ORDER BY meta_created_at
`

func (q *Queries) ListNodesByCreatedSince(ctx context.Context, createdSince pgtype.Timestamptz) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByCreatedSince, createdSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.ApiVersions,
			&i.ApiEndpoints,
			&i.Caps,
			&i.Services,
			&i.Clocks,
			&i.Interfaces,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesPaginated = `-- name: ListNodesPaginated :many
SELECT id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version, meta_created_at FROM nodes
WHERE id >= $1
ORDER BY id
LIMIT $2
`

type ListNodesPaginatedParams struct {
	StartingID uuid.UUID
	PageSize   int32
}

func (q *Queries) ListNodesPaginated(ctx context.Context, arg ListNodesPaginatedParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesPaginated, arg.StartingID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.ApiVersions,
			&i.ApiEndpoints,
			&i.Caps,
			&i.Services,
			&i.Clocks,
			&i.Interfaces,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNode = `-- name: UpsertNode :one
INSERT INTO nodes (
    id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) 
DO UPDATE
SET
    resource_version = EXCLUDED.resource_version,
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    api_versions = EXCLUDED.api_versions,
    api_endpoints = EXCLUDED.api_endpoints,
    caps = EXCLUDED.caps,
    services = EXCLUDED.services,
    clocks = EXCLUDED.clocks,
    interfaces = EXCLUDED.interfaces
WHERE
    nodes.meta_api_version = EXCLUDED.meta_api_version
    AND nodes.resource_version < EXCLUDED.resource_version
RETURNING id, resource_version, label, description, tags, api_versions, api_endpoints, caps, services, clocks, interfaces, meta_api_version, meta_created_at
`

type UpsertNodeParams struct {
	ID              uuid.UUID
	ResourceVersion string
	Label           string
	Description     *string
	Tags            []byte
	ApiVersions     []string
	ApiEndpoints    []byte
	Caps            []byte
	Services        []byte
	Clocks          []byte
	Interfaces      []byte
	MetaApiVersion  string
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.ID,
		arg.ResourceVersion,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.ApiVersions,
		arg.ApiEndpoints,
		arg.Caps,
		arg.Services,
		arg.Clocks,
		arg.Interfaces,
		arg.MetaApiVersion,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.ApiVersions,
		&i.ApiEndpoints,
		&i.Caps,
		&i.Services,
		&i.Clocks,
		&i.Interfaces,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}
