// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receivers.sql

package nmosdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReceiver = `-- name: GetReceiver :one
SELECT id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at FROM receivers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReceiver(ctx context.Context, id uuid.UUID) (Receiver, error) {
	row := q.db.QueryRow(ctx, getReceiver, id)
	var i Receiver
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.DeviceID,
		&i.Transport,
		&i.InterfaceBindings,
		&i.SubscriptionSender,
		&i.SubscriptionActive,
		&i.Format,
		&i.Caps,
		&i.MetaUserLabel,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const listReceivers = `-- name: ListReceivers :many
SELECT id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at FROM receivers
ORDER BY id
`

func (q *Queries) ListReceivers(ctx context.Context) ([]Receiver, error) {
	rows, err := q.db.Query(ctx, listReceivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiver
	for rows.Next() {
		var i Receiver
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.DeviceID,
			&i.Transport,
			&i.InterfaceBindings,
			&i.SubscriptionSender,
			&i.SubscriptionActive,
			&i.Format,
			&i.Caps,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiversByCreatedSince = `-- name: ListReceiversByCreatedSince :many
SELECT id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at FROM receivers
WHERE meta_created_at >= $1
ORDER BY meta_created_at
`

func (q *Queries) ListReceiversByCreatedSince(ctx context.Context, createdSince pgtype.Timestamptz) ([]Receiver, error) {
	rows, err := q.db.Query(ctx, listReceiversByCreatedSince, createdSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiver
	for rows.Next() {
		var i Receiver
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.DeviceID,
			&i.Transport,
			&i.InterfaceBindings,
			&i.SubscriptionSender,
			&i.SubscriptionActive,
			&i.Format,
			&i.Caps,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiversByDeviceID = `-- name: ListReceiversByDeviceID :many
SELECT id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at FROM receivers
WHERE device_id = $1
ORDER BY id
`

func (q *Queries) ListReceiversByDeviceID(ctx context.Context, deviceID *uuid.UUID) ([]Receiver, error) {
	rows, err := q.db.Query(ctx, listReceiversByDeviceID, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiver
	for rows.Next() {
		var i Receiver
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.DeviceID,
			&i.Transport,
			&i.InterfaceBindings,
			&i.SubscriptionSender,
			&i.SubscriptionActive,
			&i.Format,
			&i.Caps,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiversByDeviceIDAndTransport = `-- name: ListReceiversByDeviceIDAndTransport :many
SELECT id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at FROM receivers
WHERE device_id = $1 AND transport = $2
ORDER BY id
`

type ListReceiversByDeviceIDAndTransportParams struct {
	DeviceID  *uuid.UUID
	Transport *string
}

func (q *Queries) ListReceiversByDeviceIDAndTransport(ctx context.Context, arg ListReceiversByDeviceIDAndTransportParams) ([]Receiver, error) {
	rows, err := q.db.Query(ctx, listReceiversByDeviceIDAndTransport, arg.DeviceID, arg.Transport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiver
	for rows.Next() {
		var i Receiver
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.DeviceID,
			&i.Transport,
			&i.InterfaceBindings,
			&i.SubscriptionSender,
			&i.SubscriptionActive,
			&i.Format,
			&i.Caps,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiversByTransport = `-- name: ListReceiversByTransport :many
SELECT id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at FROM receivers
WHERE transport = $1
ORDER BY id
`

func (q *Queries) ListReceiversByTransport(ctx context.Context, transport *string) ([]Receiver, error) {
	rows, err := q.db.Query(ctx, listReceiversByTransport, transport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiver
	for rows.Next() {
		var i Receiver
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.DeviceID,
			&i.Transport,
			&i.InterfaceBindings,
			&i.SubscriptionSender,
			&i.SubscriptionActive,
			&i.Format,
			&i.Caps,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiversPaginated = `-- name: ListReceiversPaginated :many
SELECT id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at FROM receivers
WHERE id >= $1
ORDER BY id
LIMIT $2
`

type ListReceiversPaginatedParams struct {
	StartingID uuid.UUID
	PageSize   int32
}

func (q *Queries) ListReceiversPaginated(ctx context.Context, arg ListReceiversPaginatedParams) ([]Receiver, error) {
	rows, err := q.db.Query(ctx, listReceiversPaginated, arg.StartingID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiver
	for rows.Next() {
		var i Receiver
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.DeviceID,
			&i.Transport,
			&i.InterfaceBindings,
			&i.SubscriptionSender,
			&i.SubscriptionActive,
			&i.Format,
			&i.Caps,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReceiver = `-- name: UpsertReceiver :one
INSERT INTO receivers (
    id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (id) 
DO UPDATE
SET
    resource_version = EXCLUDED.resource_version,
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    device_id = EXCLUDED.device_id,
    transport = EXCLUDED.transport,
    interface_bindings = EXCLUDED.interface_bindings,
    subscription_sender = EXCLUDED.subscription_sender,
    format = EXCLUDED.format,
    caps = EXCLUDED.caps,
    meta_user_label = EXCLUDED.meta_user_label
WHERE
    receivers.meta_api_version = EXCLUDED.meta_api_version
    AND receivers.resource_version < EXCLUDED.resource_version
RETURNING id, resource_version, label, description, tags, device_id, transport, interface_bindings, subscription_sender, subscription_active, format, caps, meta_user_label, meta_api_version, meta_created_at
`

type UpsertReceiverParams struct {
	ID                 uuid.UUID
	ResourceVersion    string
	Label              string
	Description        *string
	Tags               []byte
	DeviceID           *uuid.UUID
	Transport          *string
	InterfaceBindings  []string
	SubscriptionSender *uuid.UUID
	SubscriptionActive pgtype.Bool
	Format             *string
	Caps               []byte
	MetaUserLabel      *string
	MetaApiVersion     string
}

func (q *Queries) UpsertReceiver(ctx context.Context, arg UpsertReceiverParams) (Receiver, error) {
	row := q.db.QueryRow(ctx, upsertReceiver,
		arg.ID,
		arg.ResourceVersion,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.DeviceID,
		arg.Transport,
		arg.InterfaceBindings,
		arg.SubscriptionSender,
		arg.SubscriptionActive,
		arg.Format,
		arg.Caps,
		arg.MetaUserLabel,
		arg.MetaApiVersion,
	)
	var i Receiver
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.DeviceID,
		&i.Transport,
		&i.InterfaceBindings,
		&i.SubscriptionSender,
		&i.SubscriptionActive,
		&i.Format,
		&i.Caps,
		&i.MetaUserLabel,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}
