// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sender_groups.sql

package nmosdb

import (
	"context"

	"github.com/google/uuid"
)

const listSenderGroupsByDeviceID = `-- name: ListSenderGroupsByDeviceID :many
SELECT
    sg.device_id,
    sg.group_name,
    sg.group_member,
    s.id, s.resource_version, s.label, s.description, s.tags, s.caps, s.flow_id, s.transport, s.device_id, s.manifest_href, s.interface_bindings, s.subscription_receiver, s.subscription_active, s.transport_file, s.meta_user_label, s.meta_api_version, s.meta_created_at
FROM sender_groups sg
JOIN senders s
    ON s.id = sg.sender_id
WHERE
    sg.device_id = $1
`

type ListSenderGroupsByDeviceIDRow struct {
	DeviceID    *uuid.UUID
	GroupName   string
	GroupMember string
	Sender      Sender
}

func (q *Queries) ListSenderGroupsByDeviceID(ctx context.Context, deviceID *uuid.UUID) ([]ListSenderGroupsByDeviceIDRow, error) {
	rows, err := q.db.Query(ctx, listSenderGroupsByDeviceID, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSenderGroupsByDeviceIDRow
	for rows.Next() {
		var i ListSenderGroupsByDeviceIDRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.GroupName,
			&i.GroupMember,
			&i.Sender.ID,
			&i.Sender.ResourceVersion,
			&i.Sender.Label,
			&i.Sender.Description,
			&i.Sender.Tags,
			&i.Sender.Caps,
			&i.Sender.FlowID,
			&i.Sender.Transport,
			&i.Sender.DeviceID,
			&i.Sender.ManifestHref,
			&i.Sender.InterfaceBindings,
			&i.Sender.SubscriptionReceiver,
			&i.Sender.SubscriptionActive,
			&i.Sender.TransportFile,
			&i.Sender.MetaUserLabel,
			&i.Sender.MetaApiVersion,
			&i.Sender.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSenderGroupsBySenderID = `-- name: ListSenderGroupsBySenderID :many
SELECT sg.device_id, sg.group_name, sg.group_member, sg.sender_id
FROM sender_groups sg
WHERE
    sg.sender_id = $1
`

func (q *Queries) ListSenderGroupsBySenderID(ctx context.Context, senderID uuid.UUID) ([]SenderGroup, error) {
	rows, err := q.db.Query(ctx, listSenderGroupsBySenderID, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SenderGroup
	for rows.Next() {
		var i SenderGroup
		if err := rows.Scan(
			&i.DeviceID,
			&i.GroupName,
			&i.GroupMember,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
