// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: senders.sql

package nmosdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSender = `-- name: GetSender :one
SELECT id, resource_version, label, description, tags, caps, flow_id, transport, device_id, manifest_href, interface_bindings, subscription_receiver, subscription_active, transport_file, meta_user_label, meta_api_version, meta_created_at FROM senders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSender(ctx context.Context, id uuid.UUID) (Sender, error) {
	row := q.db.QueryRow(ctx, getSender, id)
	var i Sender
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Caps,
		&i.FlowID,
		&i.Transport,
		&i.DeviceID,
		&i.ManifestHref,
		&i.InterfaceBindings,
		&i.SubscriptionReceiver,
		&i.SubscriptionActive,
		&i.TransportFile,
		&i.MetaUserLabel,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const listSenders = `-- name: ListSenders :many
SELECT id, resource_version, label, description, tags, caps, flow_id, transport, device_id, manifest_href, interface_bindings, subscription_receiver, subscription_active, transport_file, meta_user_label, meta_api_version, meta_created_at FROM senders
ORDER BY id
`

func (q *Queries) ListSenders(ctx context.Context) ([]Sender, error) {
	rows, err := q.db.Query(ctx, listSenders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sender
	for rows.Next() {
		var i Sender
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Caps,
			&i.FlowID,
			&i.Transport,
			&i.DeviceID,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiver,
			&i.SubscriptionActive,
			&i.TransportFile,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendersByCreatedSince = `-- name: ListSendersByCreatedSince :many
SELECT id, resource_version, label, description, tags, caps, flow_id, transport, device_id, manifest_href, interface_bindings, subscription_receiver, subscription_active, transport_file, meta_user_label, meta_api_version, meta_created_at FROM senders
WHERE meta_created_at >= $1
ORDER BY meta_created_at
`

func (q *Queries) ListSendersByCreatedSince(ctx context.Context, createdSince pgtype.Timestamptz) ([]Sender, error) {
	rows, err := q.db.Query(ctx, listSendersByCreatedSince, createdSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sender
	for rows.Next() {
		var i Sender
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Caps,
			&i.FlowID,
			&i.Transport,
			&i.DeviceID,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiver,
			&i.SubscriptionActive,
			&i.TransportFile,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendersByDeviceIDTransportAndFormat = `-- name: ListSendersByDeviceIDTransportAndFormat :many
SELECT s.id, s.resource_version, s.label, s.description, s.tags, s.caps, s.flow_id, s.transport, s.device_id, s.manifest_href, s.interface_bindings, s.subscription_receiver, s.subscription_active, s.transport_file, s.meta_user_label, s.meta_api_version, s.meta_created_at FROM senders s
JOIN flows f ON s.flow_id = f.id
JOIN sources src ON f.source_id = src.id
WHERE s.device_id = $1 AND s.transport = $2 AND f.format = $3 AND src.format = $4
ORDER BY s.id
`

type ListSendersByDeviceIDTransportAndFormatParams struct {
	DeviceID     *uuid.UUID
	Transport    string
	FlowFormat   string
	SourceFormat string
}

func (q *Queries) ListSendersByDeviceIDTransportAndFormat(ctx context.Context, arg ListSendersByDeviceIDTransportAndFormatParams) ([]Sender, error) {
	rows, err := q.db.Query(ctx, listSendersByDeviceIDTransportAndFormat,
		arg.DeviceID,
		arg.Transport,
		arg.FlowFormat,
		arg.SourceFormat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sender
	for rows.Next() {
		var i Sender
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Caps,
			&i.FlowID,
			&i.Transport,
			&i.DeviceID,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiver,
			&i.SubscriptionActive,
			&i.TransportFile,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendersByTransport = `-- name: ListSendersByTransport :many
SELECT id, resource_version, label, description, tags, caps, flow_id, transport, device_id, manifest_href, interface_bindings, subscription_receiver, subscription_active, transport_file, meta_user_label, meta_api_version, meta_created_at FROM senders
WHERE transport = $1
ORDER BY id
`

func (q *Queries) ListSendersByTransport(ctx context.Context, transport string) ([]Sender, error) {
	rows, err := q.db.Query(ctx, listSendersByTransport, transport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sender
	for rows.Next() {
		var i Sender
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Caps,
			&i.FlowID,
			&i.Transport,
			&i.DeviceID,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiver,
			&i.SubscriptionActive,
			&i.TransportFile,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendersByTransportAndFlowFormat = `-- name: ListSendersByTransportAndFlowFormat :many
SELECT s.id, s.resource_version, s.label, s.description, s.tags, s.caps, s.flow_id, s.transport, s.device_id, s.manifest_href, s.interface_bindings, s.subscription_receiver, s.subscription_active, s.transport_file, s.meta_user_label, s.meta_api_version, s.meta_created_at FROM senders s
JOIN flows f ON s.flow_id = f.id
JOIN sources src ON f.source_id = src.id
WHERE s.transport = $1 AND f.format = $2 AND src.format = $3
ORDER BY s.id
`

type ListSendersByTransportAndFlowFormatParams struct {
	Transport    string
	FlowFormat   string
	SourceFormat string
}

func (q *Queries) ListSendersByTransportAndFlowFormat(ctx context.Context, arg ListSendersByTransportAndFlowFormatParams) ([]Sender, error) {
	rows, err := q.db.Query(ctx, listSendersByTransportAndFlowFormat, arg.Transport, arg.FlowFormat, arg.SourceFormat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sender
	for rows.Next() {
		var i Sender
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Caps,
			&i.FlowID,
			&i.Transport,
			&i.DeviceID,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiver,
			&i.SubscriptionActive,
			&i.TransportFile,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendersPaginated = `-- name: ListSendersPaginated :many
SELECT id, resource_version, label, description, tags, caps, flow_id, transport, device_id, manifest_href, interface_bindings, subscription_receiver, subscription_active, transport_file, meta_user_label, meta_api_version, meta_created_at FROM senders
WHERE id >= $1
ORDER BY id
LIMIT $2
`

type ListSendersPaginatedParams struct {
	StartingID uuid.UUID
	PageSize   int32
}

func (q *Queries) ListSendersPaginated(ctx context.Context, arg ListSendersPaginatedParams) ([]Sender, error) {
	rows, err := q.db.Query(ctx, listSendersPaginated, arg.StartingID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sender
	for rows.Next() {
		var i Sender
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Caps,
			&i.FlowID,
			&i.Transport,
			&i.DeviceID,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiver,
			&i.SubscriptionActive,
			&i.TransportFile,
			&i.MetaUserLabel,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSender = `-- name: UpsertSender :one
INSERT INTO senders (
    id, resource_version, label, description, tags, caps, flow_id, transport, device_id, manifest_href, interface_bindings, subscription_receiver, subscription_active, transport_file, meta_user_label, meta_api_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (id) 
DO UPDATE
SET
    resource_version = EXCLUDED.resource_version,
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    caps = EXCLUDED.caps,
    flow_id = EXCLUDED.flow_id,
    transport = EXCLUDED.transport,
    device_id = EXCLUDED.device_id,
    manifest_href = EXCLUDED.manifest_href,
    interface_bindings = EXCLUDED.interface_bindings,
    subscription_receiver = EXCLUDED.subscription_receiver,
    subscription_active = EXCLUDED.subscription_active,
    transport_file = EXCLUDED.transport_file,
    meta_user_label = EXCLUDED.meta_user_label
WHERE
    senders.meta_api_version = EXCLUDED.meta_api_version
    AND senders.resource_version < EXCLUDED.resource_version
RETURNING id, resource_version, label, description, tags, caps, flow_id, transport, device_id, manifest_href, interface_bindings, subscription_receiver, subscription_active, transport_file, meta_user_label, meta_api_version, meta_created_at
`

type UpsertSenderParams struct {
	ID                   uuid.UUID
	ResourceVersion      string
	Label                string
	Description          *string
	Tags                 []byte
	Caps                 []byte
	FlowID               *uuid.UUID
	Transport            string
	DeviceID             *uuid.UUID
	ManifestHref         *string
	InterfaceBindings    []string
	SubscriptionReceiver *uuid.UUID
	SubscriptionActive   pgtype.Bool
	TransportFile        []byte
	MetaUserLabel        *string
	MetaApiVersion       string
}

func (q *Queries) UpsertSender(ctx context.Context, arg UpsertSenderParams) (Sender, error) {
	row := q.db.QueryRow(ctx, upsertSender,
		arg.ID,
		arg.ResourceVersion,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Caps,
		arg.FlowID,
		arg.Transport,
		arg.DeviceID,
		arg.ManifestHref,
		arg.InterfaceBindings,
		arg.SubscriptionReceiver,
		arg.SubscriptionActive,
		arg.TransportFile,
		arg.MetaUserLabel,
		arg.MetaApiVersion,
	)
	var i Sender
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Caps,
		&i.FlowID,
		&i.Transport,
		&i.DeviceID,
		&i.ManifestHref,
		&i.InterfaceBindings,
		&i.SubscriptionReceiver,
		&i.SubscriptionActive,
		&i.TransportFile,
		&i.MetaUserLabel,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}
