// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package nmosdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSource = `-- name: GetSource :one
SELECT id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version, meta_created_at FROM sources
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.GrainRate,
		&i.Caps,
		&i.DeviceID,
		&i.Parents,
		&i.ClockName,
		&i.Format,
		&i.AudioChannels,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version, meta_created_at FROM sources
ORDER BY id
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.GrainRate,
			&i.Caps,
			&i.DeviceID,
			&i.Parents,
			&i.ClockName,
			&i.Format,
			&i.AudioChannels,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByCreatedSince = `-- name: ListSourcesByCreatedSince :many
SELECT id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version, meta_created_at FROM sources
WHERE meta_created_at >= $1
ORDER BY meta_created_at
`

func (q *Queries) ListSourcesByCreatedSince(ctx context.Context, createdSince pgtype.Timestamptz) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByCreatedSince, createdSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.GrainRate,
			&i.Caps,
			&i.DeviceID,
			&i.Parents,
			&i.ClockName,
			&i.Format,
			&i.AudioChannels,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByDeviceID = `-- name: ListSourcesByDeviceID :many
SELECT id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version, meta_created_at FROM sources
WHERE device_id = $1
ORDER BY id
`

func (q *Queries) ListSourcesByDeviceID(ctx context.Context, deviceID *uuid.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByDeviceID, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.GrainRate,
			&i.Caps,
			&i.DeviceID,
			&i.Parents,
			&i.ClockName,
			&i.Format,
			&i.AudioChannels,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByDeviceIDAndFormat = `-- name: ListSourcesByDeviceIDAndFormat :many
SELECT id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version, meta_created_at FROM sources
WHERE device_id = $1 AND format = $2
ORDER BY id
`

type ListSourcesByDeviceIDAndFormatParams struct {
	DeviceID *uuid.UUID
	Format   string
}

func (q *Queries) ListSourcesByDeviceIDAndFormat(ctx context.Context, arg ListSourcesByDeviceIDAndFormatParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByDeviceIDAndFormat, arg.DeviceID, arg.Format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.GrainRate,
			&i.Caps,
			&i.DeviceID,
			&i.Parents,
			&i.ClockName,
			&i.Format,
			&i.AudioChannels,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByFormat = `-- name: ListSourcesByFormat :many
SELECT id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version, meta_created_at FROM sources
WHERE format = $1
ORDER BY id
`

func (q *Queries) ListSourcesByFormat(ctx context.Context, format string) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByFormat, format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ResourceVersion,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.GrainRate,
			&i.Caps,
			&i.DeviceID,
			&i.Parents,
			&i.ClockName,
			&i.Format,
			&i.AudioChannels,
			&i.MetaApiVersion,
			&i.MetaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (
    id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) 
DO UPDATE
SET
    resource_version = EXCLUDED.resource_version,
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    grain_rate = EXCLUDED.grain_rate,
    caps = EXCLUDED.caps,
    device_id = EXCLUDED.device_id,
    parents = EXCLUDED.parents,
    clock_name = EXCLUDED.clock_name,
    format = EXCLUDED.format,
    audio_channels = EXCLUDED.audio_channels
WHERE
    sources.meta_api_version = EXCLUDED.meta_api_version
    AND sources.resource_version < EXCLUDED.resource_version
RETURNING id, resource_version, label, description, tags, grain_rate, caps, device_id, parents, clock_name, format, audio_channels, meta_api_version, meta_created_at
`

type UpsertSourceParams struct {
	ID              uuid.UUID
	ResourceVersion string
	Label           string
	Description     *string
	Tags            []byte
	GrainRate       []byte
	Caps            []byte
	DeviceID        *uuid.UUID
	Parents         []string
	ClockName       *string
	Format          string
	AudioChannels   []byte
	MetaApiVersion  string
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, upsertSource,
		arg.ID,
		arg.ResourceVersion,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.GrainRate,
		arg.Caps,
		arg.DeviceID,
		arg.Parents,
		arg.ClockName,
		arg.Format,
		arg.AudioChannels,
		arg.MetaApiVersion,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ResourceVersion,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.GrainRate,
		&i.Caps,
		&i.DeviceID,
		&i.Parents,
		&i.ClockName,
		&i.Format,
		&i.AudioChannels,
		&i.MetaApiVersion,
		&i.MetaCreatedAt,
	)
	return i, err
}
